name: 编译安卓内核
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install repo tool
        run: |
          mkdir ~/bin
          PATH=~/bin:$PATH
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Initialize repo project
        run: |
          cd android-4.14-dev
          ~/bin/repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b q-goldfish-android-goldfish-4.14-dev
          cp ../custom-manifest/default.xml .repo/manifests/
          ~/bin/repo sync -c --no-tags --no-clone-bundle -j`nproc`
      - name: Apply patches
        run: |
          git apply ./patch/cve-2019-2215.patch

      - name: Configure build
        run: |
          BUILD_CONFIG=./build-configs/goldfish.x86_64.kasan

      - name: Build kernel
        run: |
          build/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-artifacts
          path: |
            out/arch/x86_64/boot/Image.gz-dtb
            out/arch/x86_64/boot/boot.img
