name: 编译安卓内核
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install build dependencies
        run: |
          # sudo apt-get update && sudo apt-get install -y build-essential
          sudo apt-get update && sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig wget python3 git make clang gcc bc

      - name: Install repo tool
        run: |
          mkdir ~/bin
          PATH=~/bin:$PATH
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Initialize repo project
        run: |
          cd android-4.14-dev
          ~/bin/repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b q-goldfish-android-goldfish-4.14-dev
          cp ../custom-manifest/default.xml .repo/manifests/
          ~/bin/repo sync -c --no-tags --no-clone-bundle -j`nproc`
      - name: Apply patches
        run: |
          # tar --exclude='.repo/' --exclude='.git/' -cjvf archive.tar.bz2 android-4.14-dev
          cd android-4.14-dev
          git apply ../patch/cve-2019-2215.patch
          sed -i 's/YYLTYPE yylloc;/extern YYLTYPE yylloc;/' ./goldfish/scripts/dtc/dtc-lexer.lex.c_shipped
          # find ./ | tee find-dir.log

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: find-dir
      #     path: ./android-4.14-dev/find-dir.log

      # - name: Configure build
      #   run: |
      #     echo "`pwd`"

      - name: Build kernel
        run: |
          cd android-4.14-dev
          BUILD_CONFIG=../build-configs/goldfish.x86_64.kasan build/build.sh
          tar -cjf archive.tar.bz2 android-4.14-dev/out/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-artifacts
          path: |
            # android-4.14-dev/out/arch/x86_64/boot/Image.gz-dtb
            # android-4.14-dev/out/arch/x86_64/boot/boot.img
            android-4.14-dev/archive.tar.bz2
